### ISSUE TITLE
Create CI/CD Integration Examples

### ISSUE THREAD

**Issue by mralanlee** [mralanlee/mille#33]
**Type**: Documentation
**Priority**: Medium
**Labels**: documentation, integration, ci/cd

**Description**:
Create comprehensive examples and templates for integrating with popular CI/CD systems.

**Acceptance Criteria**:
- [ ] GitHub Actions workflow templates
- [ ] GitLab CI configuration examples
- [ ] Jenkins pipeline scripts
- [ ] Azure DevOps pipeline templates
- [ ] Terraform Cloud integration guide

**Implementation Details**:
1. Create example workflows:
   ```yaml
   # .github/workflows/terraform-visualize.yml
   name: Terraform Visualization
   on:
     pull_request:
       paths: ['**/*.tf']
   
   jobs:
     visualize:
       runs-on: ubuntu-latest
       steps:
         - uses: actions/checkout@v3
         - name: Generate Plan
           run: terraform plan -out=plan.tfplan
         - name: Convert to JSON
           run: terraform show -json plan.tfplan > plan.json
         - name: Generate Visualization
           uses: mralanlee/mille-action@v1
           with:
             plan-file: plan.json
   ```

2. Add integration documentation
3. Create custom GitHub Action

**Testing Requirements**:
- Test all CI/CD examples
- Validate integration documentation
- Test custom actions/plugins
