### ISSUE TITLE
Set Up CI/CD Pipeline

### ISSUE THREAD

**Issue by mralanlee** [mralanlee/mille#6]
**Type**: Setup
**Priority**: Medium
**Labels**: setup, ci/cd

**Description**:
Configure GitHub Actions for continuous integration and testing.

**Acceptance Criteria**:
- [ ] Create GitHub Actions workflow for Go tests
- [ ] Add Python testing to workflow
- [ ] Add Svelte build verification
- [ ] Configure code coverage reporting
- [ ] Set up branch protection rules

**Implementation Details**:
1. Create `.github/workflows/ci.yml`:
   ```yaml
   name: CI

   on:
     push:
       branches: [ main, develop ]
     pull_request:
       branches: [ main ]

   jobs:
     test-go:
       runs-on: ubuntu-latest
       steps:
         - uses: actions/checkout@v3
         - uses: actions/setup-go@v4
           with:
             go-version: '1.21'
         - run: go test ./...

     test-python:
       runs-on: ubuntu-latest
       steps:
         - uses: actions/checkout@v3
         - uses: actions/setup-python@v4
           with:
             python-version: '3.11'
         - run: |
             cd python
             pip install -r requirements.txt
             python -m pytest

     build-web:
       runs-on: ubuntu-latest
       steps:
         - uses: actions/checkout@v3
         - uses: actions/setup-node@v3
           with:
             node-version: '18'
         - run: |
             cd web
             npm ci
             npm run build
   ```

**Resources**:
- [GitHub Actions Documentation](https://docs.github.com/en/actions)
- [Go Testing in GitHub Actions](https://github.com/actions/setup-go)
